twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        photo_dir: 'uploads/photos/'

when@test:
    twig:
        strict_variables: true
