#Version of yaml
version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/app

    php:
        build:
            context: .
            dockerfile: ./docker/php/PHP.Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./:/app

    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS:-root}
            MYSQL_USER: ${DB_USER:-secret}
        restart: always
        ports:
            - 3306:3306

    mailer:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:80

    redis:
        image: redis:5-alpine
        ports:
            - 6379:6379

volumes:
    mysqldata: {}